DROP TABLE PAYS;
DROP TABLE PARTICIPE_A;
DROP TABLE JEUX_OLYMPIQUE;
DROP TABLE FAIT_PARTIE;
DROP TABLE FAIT;
DROP TABLE EQUIPE;
DROP TABLE ATHLETE;

CREATE TABLE ATHLETE (
  PRIMARY KEY (id_Athlete),
  id_Athlete VARCHAR(42) NOT NULL,
  nom        VARCHAR(42),
  prenom     VARCHAR(42),
  sexe       VARCHAR(42),
  force      VARCHAR(42),
  endurance  VARCHAR(42),
  agilite    VARCHAR(42),
  score      VARCHAR(42),
  nom_P      VARCHAR(42) NOT NULL
);

CREATE TABLE EPREUVE (
  PRIMARY KEY (id_Epreuve),
  id_Epreuve   VARCHAR(42) NOT NULL,
  sport        VARCHAR(42),
  sexe         VARCHAR(42),
  lieu_Epreuve VARCHAR(42),
  annee        VARCHAR(42) NOT NULL
);

CREATE TABLE EQUIPE (
  PRIMARY KEY (id_Equipe),
  id_Equipe   VARCHAR(42) NOT NULL,
  nom_E       VARCHAR(42),
  nb_Athletes VARCHAR(42),
  force_E     VARCHAR(42),
  agilite_E   VARCHAR(42),
  endurance_E VARCHAR(42),
  nom_P       VARCHAR(42) NOT NULL
);

CREATE TABLE FAIT (
  PRIMARY KEY (id_Equipe, id_Epreuve),
  id_Equipe  VARCHAR(42) NOT NULL,
  id_Epreuve VARCHAR(42) NOT NULL
);

CREATE TABLE FAIT_PARTIE (
  PRIMARY KEY (id_Athlete, id_Equipe),
  id_Athlete VARCHAR(42) NOT NULL,
  id_Equipe  VARCHAR(42) NOT NULL
);

CREATE TABLE JEUX_OLYMPIQUE (
  PRIMARY KEY (annee),
  annee VARCHAR(42) NOT NULL,
  lieu  VARCHAR(42)
);

CREATE TABLE PARTICIPE_A (
  PRIMARY KEY (id_Athlete, id_Epreuve),
  id_Athlete VARCHAR(42) NOT NULL,
  id_Epreuve VARCHAR(42) NOT NULL
);

CREATE TABLE PAYS (
  PRIMARY KEY (nom_P),
  nom_P   VARCHAR(42) NOT NULL,
  score_P VARCHAR(42)
);

ALTER TABLE ATHLETE ADD FOREIGN KEY (nom_P) REFERENCES PAYS (nom_P);

ALTER TABLE EPREUVE ADD FOREIGN KEY (annee) REFERENCES JEUX_OLYMPIQUE (annee);

ALTER TABLE Equipe ADD FOREIGN KEY (nom_P) REFERENCES PAYS (nom_P);

ALTER TABLE FAIT ADD FOREIGN KEY (id_Epreuve) REFERENCES EPREUVE (id_Epreuve);
ALTER TABLE FAIT ADD FOREIGN KEY (id_Equipe) REFERENCES EQUIPE (id_Equipe);
ALTER TABLE FAIT_PARTIE ADD FOREIGN KEY (id_Equipe) REFERENCES EQUIPE (id_Equipe);
ALTER TABLE FAIT_PARTIE ADD FOREIGN KEY (id_Athlete) REFERENCES ATHLETE (id_Athlete);

ALTER TABLE PARTICIPE_A ADD FOREIGN KEY (id_Epreuve) REFERENCES EPREUVE (id_Epreuve);
ALTER TABLE PARTICIPE_A ADD FOREIGN KEY (id_Athlete) REFERENCES ATHLETE (id_Athlete);